import {
  FaJs,
  FaPython,
  FaJava,
  FaReact,
  FaNodeJs,
  FaPhp,
  FaGitAlt,
  FaGithub,
  FaDocker,
  FaAws,
  FaAngular,
  FaVuejs,
  FaLaravel,
  FaBootstrap,
  FaGem,
  FaCode,
} from "react-icons/fa";
import {
  SiCplusplus,
  SiC,
  SiGo,
  SiRust,
  SiSwift,
  SiKotlin,
  SiTypescript,
  SiExpress,
  SiNextdotjs,
  SiTailwindcss,
  SiDjango,
  SiFlask,
  SiSpring,
  SiKubernetes,
  SiFirebase,
  SiJetbrains,
  SiNpm,
  SiYarn,
  SiDotnet,
} from "react-icons/si";

export const icons = [
  { icon: <FaJs />, color: "#F7DF1E" },
  { icon: <SiTypescript />, color: "#3178C6" },
  { icon: <FaPython />, color: "#3776AB" },
  { icon: <FaJava />, color: "#f89820" },
  { icon: <SiCplusplus />, color: "#00599C" },
  { icon: <SiC />, color: "#A8B9CC" },
  { icon: <SiDotnet />, color: "#512BD4" },
  { icon: <SiGo />, color: "#00ADD8" },
  { icon: <SiRust />, color: "#DEA584" },
  { icon: <FaPhp />, color: "#777BB4" },
  { icon: <FaGem />, color: "#CC342D" },
  { icon: <SiSwift />, color: "#F05138" },
  { icon: <SiKotlin />, color: "#7F52FF" },
  { icon: <FaReact />, color: "#61DBFB" },
  { icon: <FaAngular />, color: "#DD0031" },
  { icon: <FaVuejs />, color: "#42B883" },
  { icon: <FaNodeJs />, color: "#3C873A" },
  { icon: <SiExpress />, color: "#FFFFFF" },
  { icon: <SiNextdotjs />, color: "#FFFFFF" },
  { icon: <SiTailwindcss />, color: "#06B6D4" },
  { icon: <FaBootstrap />, color: "#7952B3" },
  { icon: <SiDjango />, color: "#092E20" },
  { icon: <SiFlask />, color: "#FFFFFF" },
  { icon: <FaLaravel />, color: "#FF2D20" },
  { icon: <SiSpring />, color: "#6DB33F" },
  { icon: <FaGitAlt />, color: "#F05032" },
  { icon: <FaGithub />, color: "#FFFFFF" },
  { icon: <FaDocker />, color: "#2496ED" },
  { icon: <SiKubernetes />, color: "#326CE5" },
  { icon: <SiFirebase />, color: "#FFCA28" },
  { icon: <FaAws />, color: "#FF9900" },
  { icon: <FaCode />, color: "#007ACC" },
  { icon: <SiJetbrains />, color: "#000000" },
  { icon: <SiNpm />, color: "#CB3837" },
  { icon: <SiYarn />, color: "#2C8EBB" },
];
export default icons;